In [1]:
import numpy as np
# from numpy import *
b = np.array([[1,1,1,0,1,1],[1,1,1,0,1,0],[1,1,1,0,1,1]])
# b = np.array([1,1,0,1,1])
# print(np.mat(b))
print(b)
type(b)

[[1 1 1 0 1 1]
 [1 1 1 0 1 0]
 [1 1 1 0 1 1]]


numpy.ndarray

In [4]:
temp=np.nonzero(b[0,:])
np.array(temp)
# type(temp)
# xx=list(temp)
# type(xx)
# total=[]
# for i in range(len(b)):
#     temp=np.nonzero(b[i][:])
#     total.append(list(temp))

array([[0, 1, 2, 4, 5]], dtype=int64)

In [5]:
total=[]
total.append(temp)
total

[(array([0, 1, 2, 4, 5], dtype=int64),)]

In [6]:
total.append(temp)
total

[(array([0, 1, 2, 4, 5], dtype=int64),),
 (array([0, 1, 2, 4, 5], dtype=int64),)]

In [9]:
a=[[1,2,3],[1.4]]
b=[[1,4,5],[2,6,7],[1,2,3]]

In [11]:
total=a+b

In [12]:
total

[[1, 2, 3], [1.4], [1, 4, 5], [2, 6, 7], [1, 2, 3]]

In [13]:
list1 = ['Google', 'Runoob', 1997, 2000];

In [1]:
pp=[]

In [10]:
i=0
a=i
print(id(i))
print(id(a))
i=3
print(a)
print(i)
print(id(i))
print(id(a))

140732515791664
140732515791664
0
3
140732515791760
140732515791664


In [11]:
list1 = ['Google', 'Runoob', 1997, 2000];

In [12]:
print(1997 in list1)

True


In [24]:
l1=[[1,2,3,4]]
l1

[[1, 2, 3, 4]]

In [25]:
l=[]
l+=l1
l

[[1, 2, 3, 4]]

In [26]:
l2=[[4,3,2,1],[7,6,6,8]]
l2

[[4, 3, 2, 1], [7, 6, 6, 8]]

In [27]:
l+=l2
l

[[1, 2, 3, 4], [4, 3, 2, 1], [7, 6, 6, 8]]

In [31]:
l.sort()

TypeError: sort() takes no positional arguments

In [29]:
l

[[1, 2, 3, 4], [4, 3, 2, 1], [7, 6, 6, 8]]

In [32]:
ll=[9,6,9,3,5,2,8]

In [33]:
ll.sort()

In [38]:
l3=[[4, 2, 3, 5], [9, 3, 5, 1], [7, 0, 6, 8]]
l3

[[4, 2, 3, 5], [9, 3, 5, 1], [7, 0, 6, 8]]

In [39]:
l3[0]

[4, 2, 3, 5]

In [40]:
l3.sort()

In [42]:
l3

[[4, 2, 3, 5], [7, 0, 6, 8], [9, 3, 5, 1]]

In [43]:
l3[0].sort()

In [44]:
l3

[[2, 3, 4, 5], [7, 0, 6, 8], [9, 3, 5, 1]]

In [45]:
l4=[[4, 2, 3, 5], [7, 0, 6, 8], [9, 3, 5, 1]]
for i in range(len(l4)):
    l4[i].sort()

In [46]:
l4

[[2, 3, 4, 5], [0, 6, 7, 8], [1, 3, 5, 9]]

In [47]:
l4.sort()

In [48]:
l4

[[0, 6, 7, 8], [1, 3, 5, 9], [2, 3, 4, 5]]

In [49]:
print([0, 6, 7, 8] not in l4)

False


In [50]:
count=3
if(0<count<4):
    print("ok")
else:
    print("not ok")

ok


In [5]:
l4=[[0, 16, 7, 38], [1, 3, 5, 9], [2, 3, 4, 5]]
for i in l4:
    x = '/'.join(map(str, i))
#     x=join.map(str,i)
    print(x)

0/16/7/38
1/3/5/9
2/3/4/5


In [7]:
ll=['y','y','h']
x=map(str,ll)
print(x)

In [4]:
ll=['y','y','h','9','t','3']
for i in ll[0:len(ll):2]:
    print(i)

y
h
t
